name: Chess

on:
  issues:
    types:
      - opened

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'chess|')
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPOSITORY: ${{ github.repository }}
      USER: ${{ github.event.issue.user.login }}
    steps:
      # We <3 Ruby, so let's use it + Octokit to ease the
      # scripting and API interactions.

      #
      # I see your :eyes: :). This is all band-aids and stick tape.
      # Yep... I log like it's 1995 with random "puts" in places.
      #

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Setup Gems
      run: |
        gem install activesupport -N --silent
        gem install octokit       -N --silent
        gem install chess         -N --silent


    - name: Play
      run: |
        ruby <<- EORUBY
          require './chess.rb'

          game = Chess::Game.new()
          game.play(
            ${ISSUE_TITLE},
            ${TOKEN},
            ${REPOSITORY},
            ${ISSUE_NUMBER},
            ${USER}
          )
        EORUBY
        
# issue_title: ${{ github.event.issue.title }}
# token: ${{ secrets.GITHUB_TOKEN }}
# repository: ${REPOSITORY}
# issue_number: ${ISSUE_NUMBER}
# user: ${USER_LOGIN}
